# Generated by Django 3.1 on 2021-03-17 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_instructor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
            },
        ),
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(blank=True, choices=[('Candelaria', 'Candelaria'), ('S. Cristóbal', 'S. Cristóbal'), ('Alquízar', 'Alquízar'), ('Bahía Honda', 'Bahía Honda'), ('Artemisa', 'Artemisa'), ('Guira de Melena', 'Guira de Melena'), ('S.A. Baños', 'S.A. Baños'), ('Bauta', 'Bauta'), ('Caimito', 'Caimito'), ('Guanajay', 'Guanajay'), ('Mariel', 'Mariel')], max_length=255)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_servicio', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(blank=True, choices=[('Artemisa', 'Artemisa'), ('Habana', 'Habana'), ('P. del Río', 'P. del Río'), ('Mayabeque', 'Mayabeque'), ('Matanzas', 'Matanzas'), ('Cienfuegos', 'Cienfuegos'), ('Villa Clara', 'Villa Clara'), ('Sancti Spíritus', 'Sancti Spíritus'), ('Ciego de Ávila', 'Ciego de Ávila'), ('Camagüey', 'Camagüey'), ('Las Tunas', 'Las Tunas'), ('Granma', 'Granma'), ('Holguín', 'Holguín'), ('Santiago de Cuba', 'Santiago de Cuba'), ('Guantánamo', 'Guantánamo'), ('Isla de la Juventud', 'Isla de la Juventud')], max_length=255)),
                ('municipio', models.ManyToManyField(blank=True, to='directorio.municipio')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carnet', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('sub_total', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('atendido', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directorio.municipio')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directorio.provincia')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directorio.servicio')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
